image: Ubuntu1804

stack: node 18

branches:
  only:
    - master

cache: node_modules

install:
  - npm install

build: off

build_script:
  - npm run build:dev

test_script:
  - npm run lint && npm test
